import os
import tempfile

FILE_PATH = "failed.log"

REMOVE_STRINGS = [
"[build]",
    "/home/lux/code/language/python-cpp/src",
    '"cd /home/lux/code/language/python-cpp/build/debug/src/runtime/export && /usr/bin/ccache /usr/lib/ccache/clang++-20 -std=c++23 -O1 -g -c -emit-llvm -fno-discard-value-names -DSPDLOG_COMPILED_LIB -DDEBUG -DPYLANG_AOT_MODE -DPYLANG_USE_ARENA -DPYLANG_USE_Boehm_GC -DGC_THREADS -I /home/lux/code/language/python-cpp/src/runtime/export/../.. -I /home/lux/code/language/python-cpp/build/debug/src --gcc-toolchain=/usr -isystem /usr/lib/gcc/x86_64-linux-gnu/13/include -I /home/lux/code/language/python-cpp/src/PUBLIC -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include/ylt/thirdparty -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/ordered_map/397e/include -I /home/lux/code/language/python-cpp/src/PUBLIC -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/cpptrace/2b0e/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -I /home/lux/code/language/python-cpp/src/. -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include/ylt/thirdparty -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/ordered_map/397e/include -I /usr/include/x86_64-linux-gnu -I /home/lux/code/language/python-cpp/build/debug/src -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/spdlog/be97/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/ordered_map/397e/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/cpptrace/2b0e/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include/ylt/thirdparty -I /usr/include/x86_64-linux-gnu -Wno-everything -o"',
    'cd /home/lux/code/language/python-cpp/build/debug/src/runtime/export && /usr/bin/ccache /usr/lib/ccache/clang++-20 -std=c++23 -O1 -g -c -emit-llvm -fno-discard-value-names -DSPDLOG_COMPILED_LIB -DDEBUG -DPYLANG_AOT_MODE -DPYLANG_USE_ARENA -DPYLANG_USE_Boehm_GC -DGC_THREADS -I /runtime/export/../.. -I /home/lux/code/language/python-cpp/build/debug/src --gcc-toolchain=/usr -isystem /usr/lib/gcc/x86_64-linux-gnu/13/include -I /PUBLIC -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include/ylt/thirdparty -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/ordered_map/397e/include -I /PUBLIC -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/cpptrace/2b0e/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -I /. -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include/ylt/thirdparty -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/ordered_map/397e/include -I /usr/include/x86_64-linux-gnu -I /home/lux/code/language/python-cpp/build/debug/src -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/spdlog/be97/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/ordered_map/397e/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/cpptrace/2b0e/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include/ylt/thirdparty -I /usr/include/x86_64-linux-gnu -Wno-everything -o',
    'cd /home/lux/code/language/python-cpp/build/debug/src/runtime/export && /usr/bin/ccache /usr/lib/ccache/clang++-20 -std=c++23 -O1 -g -c -emit-llvm -fno-discard-value-names -DSPDLOG_COMPILED_LIB -DDEBUG -DPYLANG_AOT_MODE -DPYLANG_USE_ARENA -DPYLANG_USE_Boehm_GC -DGC_THREADS -I /home/lux/code/language/python-cpp/src/runtime/export/../.. -I /home/lux/code/language/python-cpp/build/debug/src --gcc-toolchain=/usr -isystem /usr/lib/gcc/x86_64-linux-gnu/13/include -I /home/lux/code/language/python-cpp/src/PUBLIC -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include/ylt/thirdparty -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/ordered_map/397e/include -I /home/lux/code/language/python-cpp/src/PUBLIC -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/cpptrace/2b0e/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -I /home/lux/code/language/python-cpp/src/. -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include/ylt/thirdparty -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/ordered_map/397e/include -I /usr/include/x86_64-linux-gnu -I /home/lux/code/language/python-cpp/build/debug/src -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/spdlog/be97/include -isystem /home/lux/code/language/python-cpp/build/debug/_deps/spdlog-build -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/ordered_map/397e/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/cpptrace/2b0e/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include/ylt/thirdparty -I /usr/include/x86_64-linux-gnu -Wno-everything -o',
    "cd /home/lux/code/language/python-cpp/build/debug/src/runtime/export && /usr/bin/ccache /usr/lib/ccache/clang++-20 -std=c++23 -O1 -g -c -emit-llvm -fno-discard-value-names -DSPDLOG_COMPILED_LIB -DDEBUG -DPYLANG_AOT_MODE -DPYLANG_USE_ARENA -DPYLANG_USE_Boehm_GC -DGC_THREADS -I /runtime/export/../.. -I /home/lux/code/language/python-cpp/build/debug/src --gcc-toolchain=/usr -isystem /usr/lib/gcc/x86_64-linux-gnu/13/include -I /PUBLIC -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include/ylt/thirdparty -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/ordered_map/397e/include -I /PUBLIC -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/cpptrace/2b0e/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -I /. -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include/ylt/thirdparty -I /home/lux/code/language/python-cpp/build/debug/.cache/CPM/ordered_map/397e/include -I /usr/include/x86_64-linux-gnu -I /home/lux/code/language/python-cpp/build/debug/src -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/spdlog/be97/include -isystem /home/lux/code/language/python-cpp/build/debug/_deps/spdlog-build -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/ordered_map/397e/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/cpptrace/2b0e/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include/ylt/thirdparty -I /usr/include/x86_64-linux-gnu -Wno-everything -o",
    """/usr/bin/ccache /usr/lib/ccache/c++ -DCMAKE_BINARY_DIR=\"/home/lux/code/language/python-cpp/build/debug\" -DCPPTRACE_STATIC_DEFINE -DGC_THREADS -DPYLANG_HAS_LLD=1 -DPYLANG_USE_ARENA -DPYLANG_USE_Boehm_GC -DSPDLOG_COMPILED_LIB -I/. -I/home/lux/code/language/python-cpp/build/debug/src -isystem /PUBLIC -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include/ylt/thirdparty -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/ordered_map/397e/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/cpptrace/2b0e/include -isystem /home/lux/code/language/python-cpp/build/debug/_deps/cpptrace-build/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/spdlog/be97/include -DALWAYS_SMALL_CLEAR_STACK -DSMALL_CLEAR_SIZE=4 -g -std=c++23 -fcolor-diagnostics -fno-omit-frame-pointer -Wall -Wextra -Wextra-semi -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wimplicit-fallthrough -Wno-sign-conversion -Wno-shadow -Wno-implicit-fallthrough -Wno-old-style-cast -Wno-deprecated-copy -Wno-missing-field-initializers -Wno-null-dereference -Wno-unknown-warning-option -MD -MT""",
    'usr/bin/ccache /usr/lib/ccache/c++ -DCMAKE_BINARY_DIR=\"/home/lux/code/language/python-cpp/build/debug\" -DCPPTRACE_STATIC_DEFINE -DGC_THREADS -DPYLANG_HAS_LLD=1 -DPYLANG_USE_ARENA -DPYLANG_USE_Boehm_GC -DSPDLOG_COMPILED_LIB -I/. -I/home/lux/code/language/python-cpp/build/debug/src -isystem /PUBLIC -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include/ylt/thirdparty -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/ordered_map/397e/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/cpptrace/2b0e/include -isystem /home/lux/code/language/python-cpp/build/debug/_deps/cpptrace-build/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/spdlog/be97/include -DALWAYS_SMALL_CLEAR_STACK -DSMALL_CLEAR_SIZE=4 -g -std=c++23 -fcolor-diagnostics -fno-omit-frame-pointer -Wall -Wextra -Wextra-semi -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wimplicit-fallthrough -Wno-sign-conversion -Wno-shadow -Wno-implicit-fallthrough -Wno-old-style-cast -Wno-deprecated-copy -Wno-missing-field-initializers -Wno-null-dereference -Wno-unknown-warning-option -MD -MT',
    "src/libpython-cpp.a  lib/libgtest.a  lib/libgtest_main.a  /usr/lib/llvm-20/lib/libLLVMLinker.a  /usr/lib/llvm-20/lib/libLLVMX86CodeGen.a  /usr/lib/llvm-20/lib/libLLVMAsmPrinter.a  /usr/lib/llvm-20/lib/libLLVMCFGuard.a  /usr/lib/llvm-20/lib/libLLVMGlobalISel.a  /usr/lib/llvm-20/lib/libLLVMIRPrinter.a  /usr/lib/llvm-20/lib/libLLVMInstrumentation.a  /usr/lib/llvm-20/lib/libLLVMSelectionDAG.a  /usr/lib/llvm-20/lib/libLLVMCodeGen.a  /usr/lib/llvm-20/lib/libLLVMScalarOpts.a  /usr/lib/llvm-20/lib/libLLVMAggressiveInstCombine.a  /usr/lib/llvm-20/lib/libLLVMInstCombine.a  /usr/lib/llvm-20/lib/libLLVMCGData.a  /usr/lib/llvm-20/lib/libLLVMBitWriter.a  /usr/lib/llvm-20/lib/libLLVMObjCARCOpts.a  /usr/lib/llvm-20/lib/libLLVMTransformUtils.a  /usr/lib/llvm-20/lib/libLLVMTarget.a  /usr/lib/llvm-20/lib/libLLVMAnalysis.a  /usr/lib/llvm-20/lib/libLLVMProfileData.a  /usr/lib/llvm-20/lib/libLLVMSymbolize.a  /usr/lib/llvm-20/lib/libLLVMDebugInfoPDB.a  /usr/lib/llvm-20/lib/libLLVMDebugInfoCodeView.a  /usr/lib/llvm-20/lib/libLLVMDebugInfoMSF.a  /usr/lib/llvm-20/lib/libLLVMDebugInfoBTF.a  /usr/lib/llvm-20/lib/libLLVMDebugInfoDWARF.a  /usr/lib/llvm-20/lib/libLLVMObject.a  /usr/lib/llvm-20/lib/libLLVMIRReader.a  /usr/lib/llvm-20/lib/libLLVMAsmParser.a  /usr/lib/llvm-20/lib/libLLVMBitReader.a  /usr/lib/llvm-20/lib/libLLVMCore.a  /usr/lib/llvm-20/lib/libLLVMRemarks.a  /usr/lib/llvm-20/lib/libLLVMBitstreamReader.a  /usr/lib/llvm-20/lib/libLLVMTextAPI.a  /usr/lib/llvm-20/lib/libLLVMX86AsmParser.a  /usr/lib/llvm-20/lib/libLLVMX86Desc.a  /usr/lib/llvm-20/lib/libLLVMCodeGenTypes.a  /usr/lib/llvm-20/lib/libLLVMMCParser.a  /usr/lib/llvm-20/lib/libLLVMX86Disassembler.a  /usr/lib/llvm-20/lib/libLLVMX86Info.a  /usr/lib/llvm-20/lib/libLLVMMCDisassembler.a  /usr/lib/llvm-20/lib/libLLVMMC.a  /usr/lib/llvm-20/lib/libLLVMBinaryFormat.a  /usr/lib/llvm-20/lib/libLLVMTargetParser.a  /usr/lib/llvm-20/lib/libLLVMSupport.a  /usr/lib/llvm-20/lib/libLLVMDemangle.a  -lrt  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libzstd.so  _deps/cpptrace-build/libcpptrace.a  _deps/libdwarf-build/src/lib/libdwarf/libdwarf.a  /usr/lib/x86_64-linux-gnu/libz.so  _deps/zstd-build/lib/libzstd.a  _deps/spdlog-build/libspdlogd.a  _deps/bdwgc-build/libgc.a  -ldl  -lm  /usr/lib/x86_64-linux-gnu/libicuuc.a  -ldl  /usr/lib/x86_64-linux-gnu/libicudata.a  /usr/lib/x86_64-linux-gnu/libgmpxx.a  /usr/lib/x86_64-linux-gnu/libgmp.a  lib/libgtest.a",
    "-DCPPTRACE_STATIC_DEFINE -DGC_THREADS -DPYLANG_HAS_LLD=1 -DPYLANG_USE_ARENA -DPYLANG_USE_Boehm_GC -DSPDLOG_COMPILED_LIB -I/. -I/home/lux/code/language/python-cpp/build/debug/src -isystem /PUBLIC -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/yalantinglibs/f7f2/include/ylt/thirdparty -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/ordered_map/397e/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/bdwgc/2bfb/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/cpptrace/2b0e/include -isystem /home/lux/code/language/python-cpp/build/debug/_deps/cpptrace-build/include -isystem /home/lux/code/language/python-cpp/build/debug/.cache/CPM/spdlog/be97/include -DALWAYS_SMALL_CLEAR_STACK -DSMALL_CLEAR_SIZE=4 -g -std=c++23 -fcolor-diagnostics -fno-omit-frame-pointer -Wall -Wextra -Wextra-semi -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wimplicit-fallthrough -Wno-sign-conversion -Wno-shadow -Wno-implicit-fallthrough -Wno-old-style-cast -Wno-deprecated-copy -Wno-missing-field-initializers -Wno-null-dereference -Wno-unknown-warning-option -MD -MT"
]


def clean_line(line: str) -> str:
    for s in REMOVE_STRINGS:
        line = line.replace(s, "")
    return line


def inplace_clean(file_path: str):
    dir_name = os.path.dirname(file_path) or "."

    with tempfile.NamedTemporaryFile("w", delete=False, dir=dir_name, encoding="utf-8") as tmp:
        tmp_name = tmp.name

        with open(file_path, "r", encoding="utf-8", errors="ignore") as fin:
            for line in fin:
                tmp.write(clean_line(line))

    # 原子替换（关键）
    os.replace(tmp_name, file_path)


if __name__ == "__main__":
    inplace_clean(FILE_PATH)
    print("原地清洗完成")